language: node_js
node_js:
  - 14 # uses version 14
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script: null

script:
  # - npm test # test the code
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: gol-developer-edition
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: eurXcv2qDU3aTn6KTPJ0s/YzvxGzlX+1bnrs8otj/3iGSRUFSMG5eJLh2tmyxtiFjtC9ZT1pZ7QcnsQjrU2rWEvc7oKvBhes6PBAxN0OAXB3cKoCErbtgXw4ya8iq8fkzlsMld1Ynv4BdzAu5hy5/5BEFmtNkMpEiPy4yuXQUuinmB+sx7r1xw7X2+upFjcNF7oTjVxZubG7ki1/xjhwtpD8cSQCr8yPCPCxZNS48CIHx6AAHSvFsg7mjU96eZqvpZAulm+GoJBDkHHO/IuCWoUoW/ZeUoZqjNHRPJqGYt1SXiTkmnLSEGYSIopwucXo2jgbv/Ck/Q9bW140nDJsowZmXv9Dao7Tf3vYjj7LCxBNNz1gkjMMHCGv9EtumO71KFYvGWEmlPwTeLp3Zre5WT6cK92HY8P7HS68H+FcFa6e2t82Qv4rLfxZZYmzG6lU4dG36spW3DA24ztRrhWFB3rosDqjRIJ+3ssX02HG39ls/9xZUwpv2TADHHB/RQr7PSlp3AQVkltDe2AkDRUD+RS9fC/CGNydPrm+UZE/FctK0qwZWdL8XP6CIkm5tIU0bnLWQ2EAX0KGygadiWHpiqWXtp+F6be5q/gG5O2Ocnitm87gstZl4RAIVT9PwZmU207scxnPFb6s4OTtJqLLCOi3pW2TqmFr9fBrf9IjWpM=
